import { ScheduleEvent, Improvement, GlossaryTerm, MagazineContent } from '@/types';

export const initialSchedule: Omit<ScheduleEvent, 'id'>[] = [
  {
    date: '2025-01-04',
    title: '二十歳の集い',
    description: 'マリアンホール 13:30〜',
    location: 'マリアンホール',
    details: [
      '【1部】聖歌・聖書朗読、祝辞（同窓会長）、集合写真撮影',
      '【2部】カフェテリア 〜15時頃、お菓子・飲み物で自由懇談',
    ],
    notes: '★集合時間の確認必要',
    isHighlight: true,
    order: 1,
  },
  {
    date: '2025-01-17',
    title: '新年の集い',
    description: '',
    notes: '',
    order: 2,
  },
  {
    date: '2025-02-27',
    title: '同窓会入会式',
    description: '卒業式リハーサル後、10:30学校着',
    location: '学校',
    details: [
      '記念品贈呈（代表生徒へ）',
      '連絡員との顔合わせ（2名×6クラス=12名）',
      '年度ごとグループLINE作成',
    ],
    notes: '',
    isHighlight: true,
    order: 3,
  },
  {
    date: '2025-03-02',
    title: '卒業式',
    description: '出席不要',
    notes: '入学式も出席不要',
    order: 4,
  },
  {
    date: '2025-04-15',
    title: 'ウニオーネ総会',
    description: '赤羽（日程は復活祭との兼ね合い）',
    location: '赤羽',
    notes: 'グループLINEに連絡が入る予定',
    order: 5,
  },
  {
    date: '2025-05-01',
    title: '同窓会誌発送',
    description: 'ウニオーネ誌同封',
    details: [
      'GW前後に発送（サレジオ祭案内のため）',
      '10月総会に向けて元担任捜索開始',
    ],
    notes: '',
    order: 6,
  },
  {
    date: '2025-06-15',
    title: 'サレジオ祭 + 30歳の集い',
    description: 'バザー土曜日 17:00〜',
    details: [
      'メモリアルルームに集合',
      '学校見学・先生と話す',
      '那須像付近で懇親会',
    ],
    notes: 'Googleフォームで出欠集計',
    order: 7,
  },
  {
    date: '2025-10-01',
    title: '同窓会総会',
    description: '還暦の方をメインターゲット',
    details: [
      '心の故郷に別刷りで案内挿入',
      '元担任を招待したい',
    ],
    notes: '★曽根さんとMTG必要（感謝の言葉→原稿化）',
    isHighlight: true,
    order: 8,
  },
];

export const initialImprovements: Omit<Improvement, 'id'>[] = [
  {
    title: '公式LINE導入',
    description: '各年度ごとの公式LINEで連絡手段を確保。一斉配信・個別対応も可能に',
    targetDate: '2025-03-31',
    notes: '川端先生、萩原さん、さとみ先生、神谷の4人で相談会を予定',
    status: 'pending',
    priority: 'high',
    order: 1,
  },
  {
    title: 'HPの同窓会ページ整備',
    description: '現在ほぼ機能していない。イベント情報、卒業生のお店紹介等を載せたい',
    targetDate: '2025-06-30',
    notes: '卒業証明書の案内しかない状態',
    status: 'pending',
    priority: 'high',
    order: 2,
  },
  {
    title: 'メール問題解決',
    description: '同窓会室のPCでしか見れない → アカウント共有 or 転送設定',
    targetDate: '2025-02-28',
    notes: '',
    status: 'pending',
    priority: 'medium',
    order: 3,
  },
  {
    title: 'Googleフォーム管理の共有',
    description: '30歳の集い申込等、現在さとみ先生が管理 → 他の人も見れるように',
    targetDate: '2025-03-31',
    notes: '',
    status: 'pending',
    priority: 'medium',
    order: 4,
  },
  {
    title: '同窓会フォルダ整理',
    description: '資料の整理・共有。学校のワークスペース契約のため外部共有が面倒',
    targetDate: '2025-03-31',
    notes: '',
    status: 'pending',
    priority: 'low',
    order: 5,
  },
  {
    title: 'SBSコスト確認',
    description: 'SBSの利用コストを確認する',
    targetDate: '2025-02-28',
    notes: '',
    status: 'pending',
    priority: 'low',
    order: 6,
  },
];

export const initialGlossary: Omit<GlossaryTerm, 'id'>[] = [
  {
    term: 'サレジアンシスターズ',
    reading: 'されじあんしすたーず',
    description: '女子修道会（正式名称：扶助者聖母会）。静岡サレジオの母体。',
    category: '組織',
    relatedTerms: ['ウニオーネ', 'サレジオ会'],
  },
  {
    term: 'サレジオ会',
    reading: 'されじおかい',
    description: '男子修道会。ドン・ボスコが創立。2025年が日本来日100周年。',
    category: '組織',
    relatedTerms: ['サレジアンシスターズ', 'サレジアンファミリー'],
  },
  {
    term: 'ウニオーネ',
    reading: 'うにおーね',
    description: 'サレジアンシスターズの同窓会世界連合（UNIONE）。日本韓国管区として1970年加盟。総会は毎年4月頃＠赤羽。',
    category: '同窓会',
    relatedTerms: ['サレジアンシスターズ'],
  },
  {
    term: 'サレジアンファミリー',
    reading: 'されじあんふぁみりー',
    description: 'サレジオ会、サレジアンシスターズ、その他関連団体の総称。',
    category: '組織',
  },
  {
    term: '心のふるさと',
    reading: 'こころのふるさと',
    description: '同窓会誌の名称。年1回発行。16ページ構成、真ん中（P8-9）がカラー。',
    category: '同窓会',
  },
  {
    term: 'ウニオーネ誌',
    reading: 'うにおーねし',
    description: '本部から届く機関誌。4月頃届き、同窓会誌と同封して5月に発送。',
    category: '同窓会',
  },
  {
    term: '連絡員',
    reading: 'れんらくいん',
    description: '各クラス2名選出。卒業時にグループLINE作成し、2年後の20歳の集いの連絡・運営を担当。',
    category: '役割',
  },
];

export const initialMagazineContents: Omit<MagazineContent, 'id'>[] = [
  {
    title: '新会長挨拶',
    pages: 1.0,
    deadline: '2025-03-15',
    assignee: '神谷',
    assigneeRole: '会長',
    status: 'not-started',
    notes: '新会長挨拶と方針、これからの構想（LINE活用等）、協力呼びかけ。曽根さんへの感謝も1/4程度入れる。',
    tasks: [
      { id: 't1', type: 'text', description: '新会長挨拶と方針', assignee: '神谷', completed: false },
      { id: 't2', type: 'text', description: '曽根さんへの感謝の言葉', assignee: '神谷', completed: false },
    ],
    order: 1,
  },
  {
    title: '理事長・校長・シスター挨拶',
    pages: 1.0,
    deadline: '2025-03-20',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '沼波先生（学園長・理事長）、新校長（4月決定）、池田シスター（顧問）。校長未定のためギリギリ。',
    tasks: [
      { id: 't3', type: 'text', description: '沼波先生（学園長・理事長）挨拶', assignee: 'さとみ先生', completed: false },
      { id: 't4', type: 'text', description: '新校長挨拶', assignee: 'さとみ先生', completed: false },
      { id: 't5', type: 'text', description: '池田シスター挨拶', assignee: 'さとみ先生', completed: false },
    ],
    order: 2,
  },
  {
    title: '末吉先生 追悼',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: '渡辺伸也先生',
    assigneeRole: '小学校の先生（卒業生）',
    status: 'not-started',
    notes: '別の機関紙に書いた文章をアレンジ。許可取り必要。写真は川端先生に依頼。',
    tasks: [
      { id: 't6', type: 'text', description: '追悼文', assignee: '渡辺伸也先生', completed: false },
      { id: 't7', type: 'photo', description: '写真', assignee: '川端先生', completed: false },
    ],
    order: 3,
  },
  {
    title: '活躍している同窓生',
    pages: 3.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '4-5人程度。橋ケ谷くん（山梨・幼稚園経営）、劇団員の子（東京地検勤務）など。神谷さんも1P使ってOK。',
    tasks: [
      { id: 't8', type: 'text', description: '橋ケ谷くん取材', assignee: 'さとみ先生', completed: false },
      { id: 't9', type: 'text', description: '劇団員の子取材', assignee: 'さとみ先生', completed: false },
      { id: 't10', type: 'photo', description: '写真収集', assignee: 'さとみ先生', completed: false },
    ],
    order: 4,
    isColorPage: true,
  },
  {
    title: '20歳の集い',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '定番。振袖などカラー映え。',
    tasks: [
      { id: 't11', type: 'text', description: '原稿', assignee: 'さとみ先生', completed: false },
      { id: 't12', type: 'photo', description: '写真', assignee: 'ミカサ写真館', completed: false },
    ],
    order: 5,
  },
  {
    title: '30歳の集い',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '',
    tasks: [
      { id: 't13', type: 'text', description: '原稿', assignee: 'さとみ先生', completed: false },
      { id: 't14', type: 'photo', description: '写真', assignee: '中村エリカさん/川端先生', completed: false },
    ],
    order: 6,
  },
  {
    title: '同窓会やりました',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '還暦の会（グランディー）、福塚先生の教え子会、曽根さん同期の会（80代約20名参加）など。',
    tasks: [
      { id: 't15', type: 'text', description: '原稿', assignee: 'さとみ先生', completed: false },
      { id: 't16', type: 'photo', description: '各クラス会から収集', assignee: 'さとみ先生', completed: false },
    ],
    order: 7,
  },
  {
    title: '新年の集い',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '',
    tasks: [
      { id: 't17', type: 'text', description: '原稿', assignee: 'さとみ先生', completed: false },
      { id: 't18', type: 'photo', description: '写真', assignee: 'さとみ先生', completed: false },
    ],
    order: 8,
  },
  {
    title: '総会報告＋サレジオ会100周年',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '2/8東京で大きな式典。サレジオ会日本韓国のHPも参照。',
    tasks: [
      { id: 't19', type: 'text', description: '総会報告', assignee: 'さとみ先生', completed: false },
      { id: 't20', type: 'text', description: '100周年紹介', assignee: 'さとみ先生', completed: false },
    ],
    order: 9,
  },
  {
    title: '会計報告・予算・活動報告',
    pages: 2.0,
    deadline: '2025-02-28',
    assignee: '役員',
    status: 'not-started',
    notes: '定番。決算報告、新年度予算、活動報告、活動計画、バザー協力ありがとう、同窓会協力費ありがとう。',
    tasks: [
      { id: 't21', type: 'data', description: '決算報告', assignee: '役員', completed: false },
      { id: 't22', type: 'data', description: '新年度予算', assignee: '役員', completed: false },
      { id: 't23', type: 'text', description: '活動報告・計画', assignee: '役員', completed: false },
    ],
    order: 10,
  },
  {
    title: '在校生の活躍',
    pages: 1.0,
    deadline: '2025-02-28',
    assignee: 'さとみ先生',
    status: 'not-started',
    notes: '最終ページ・定番。国体出場、全国大会コーラスなど。',
    tasks: [
      { id: 't24', type: 'text', description: '原稿', assignee: 'さとみ先生', completed: false },
      { id: 't25', type: 'photo', description: '写真', assignee: 'さとみ先生', completed: false },
    ],
    order: 11,
  },
];
